import { APP_PATH, ORDER_PATH, PRODUCT_PATH, SHOP_PATH } from "./path.routes"

export const APP_ROUTES = {
    HOME: `/${APP_PATH.SHOP}/${SHOP_PATH.HOME}`,
    STORE: `/${APP_PATH.SHOP}/${SHOP_PATH.PRODUCTS}/${PRODUCT_PATH.STORE}`,
    PRODUCT_DETAIL: `/${APP_PATH.SHOP}/${SHOP_PATH.PRODUCTS}/${PRODUCT_PATH.PRODUCT_DETAIL}`,
    CATEGORIES: `/${APP_PATH.SHOP}/${SHOP_PATH.PRODUCTS}/${PRODUCT_PATH.CATEGORIES}`,
    WISH_LIST: `/${APP_PATH.SHOP}/${SHOP_PATH.PRODUCTS}/${PRODUCT_PATH.WISH_LIST}`,
    CHECK_OUT: `/${APP_PATH.SHOP}/${SHOP_PATH.ORDERS}/${ORDER_PATH.CHECK_OUT}`,
    ORDER_TRACK: `/${APP_PATH.SHOP}/${SHOP_PATH.ORDERS}/${ORDER_PATH.ORDER_TRACK}`,
    ORDERS_CART: `/${APP_PATH.SHOP}/${SHOP_PATH.ORDERS}/${ORDER_PATH.ORDER_CART}`
}